### ISSUE TITLE
Stream table throws JS API error

### ISSUE THREAD

**Issue by mattrunyon** [deephaven/deephaven-core#3067]
**Description**

When using a stream table, the JS API throws an error trying to read property sortedRanges of undefined

**Steps to reproduce**
1. Use this docker-compose to start DH and a kafka service
```
version: '3.4'

services:
  server:
    image: ghcr.io/deephaven/server:${VERSION:-latest}
    ports:
      - '${PORT:-10000}:10000'
    volumes:
      - ./data:/data
      - api-cache:/cache
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx4g

  redpanda:
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    image: docker.vectorized.io/vectorized/redpanda:v22.2.2
    ports:
      - 9092:9092
      - 29092:29092

volumes:
  api-cache:
```

2. Open the web IDE and run this Python code
```python
from deephaven.stream.kafka import consumer as kc

result_stream = kc.consume({'bootstrap.servers': 'redpanda:29092'},
                        'test.topic', table_type=kc.TableType.stream(),
                        key_spec=kc.KeyValueSpec.IGNORE)
```

3. Optionally produce data to the kafka stream with `docker-compose exec redpanda rpk topic produce test.topic`. You will then type any value you want and hit enter to produce the data to the stream.

**Expected results**

No JS API error

**Actual results**

JS API error thrown in browser (data still shows up in the table when produced by Kafka)

```js
Uncaught TypeError: Cannot read properties of undefined (reading 'sortedRanges')
    at Object.$lambda$8_5 (dh-core.js:30671:130)
    at Object.$apply_9 (dh-core.js:31476:9)
    at Function.apply_214 (dh-core.js:31490:9)
    at lambda (dh-core.js:152:22)
    at Function.apply_211 (dh-core.js:31376:19)
    at lambda (dh-core.js:152:22)
    at Object.lambda$1_9 (dh-core.js:29570:3)
    at Function.onInvoke_210 (dh-core.js:29655:16)
    at lambda (dh-core.js:152:22)
    at Map.forEach (<anonymous>)
    at Object.$setSize_0 (dh-core.js:30883:24)
    at Object.lambda$31 (dh-core.js:14722:31)
    at WorkerConnection$lambda$31$Type.accept_25 [as accept] (dh-core.js:15795:9)
    at Object.$ifPresent (dh-core.js:38028:39)
    at Object.$exportedTableUpdateMessage (dh-core.js:13912:6)
    at Object.$lambda$21 (dh-core.js:14137:272)
    at Function.apply_60 (dh-core.js:15662:9)
    at lambda (dh-core.js:152:22)
    at dh-internal.js:1:1129277
    at Array.forEach (<anonymous>)
    at onMessage (dh-internal.js:1:1129256)
    at dh-internal.js:1:43913
    at Array.forEach (<anonymous>)
    at e.rawOnMessage (dh-internal.js:1:43875)
    at dh-internal.js:1:41688
    at Array.forEach (<anonymous>)
    at e.onTransportChunk (dh-internal.js:1:41563)
    at Object.$onMessage (dh-core.js:19325:33)
    at MultiplexedWebsocketTransport$3methodref$onMessage$Type.handleEvent_2 [as handleEvent] (dh-core.js:19476:10)
```

**Additional details and attachments**

The other table types for Kafka (ring/append) do not throw any errors

**Versions**
 - Deephaven: 0.18.0
