### ISSUE TITLE
Strict mode violation in JS API as a ES Module

### ISSUE THREAD

**Issue by mattrunyon** [deephaven/deephaven-core#3437]
**Description**

After the change to ESM, strict mode is enabled for the JS API which throws in some cases that may have just been silently ignored previously.

The one instance I found is related to stream tables.

**Steps to reproduce**
1. Use this docker-compose file
```
version: "3.4"

services:
  server:
    image: ghcr.io/deephaven/server:edge
    ports:
      - "${PORT:-10000}:10000"
    volumes:
      - ./data:/data
      - api-cache:/cache
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx4g -Ddeephaven.console.type=python

  redpanda:
    command:
    - redpanda
    - start
    - --smp
    - '1'
    - --reserve-memory
    - 0M
    - --overprovisioned
    - --node-id
    - '0'
    - --kafka-addr
    - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
    - --advertise-kafka-addr
    - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    image: docker.redpanda.com/vectorized/redpanda:latest
    ports:
    - 9092:9092
    - 29092:29092

volumes:
  web-tmp:
  api-cache:
```

2. Run the following Python code
```python
from deephaven.stream.kafka import consumer as kc
result_stream = kc.consume({'bootstrap.servers': 'redpanda:29092'},
                        'test.topic', table_type=kc.TableType.stream(),
                        key_spec=kc.KeyValueSpec.IGNORE)
```

3. Optionally produce data to the kafka stream with docker-compose exec redpanda rpk topic produce test.topic. You will then type any value you want and hit enter to produce the data to the stream.

**Expected results**

No JS API error.

**Actual results**

JS API error related to `TableViewportSubscription.java:127` which starts with `Column[] columnsToSub =`

```
backingJsObject: TypeError: Cannot assign to read only property '___clazz' of object '[object Array]'
      at Object.setClass (file:///Users/matt/code/deephaven.io/tools/run-examples/tmp/dh-core.js:666:14)
      at stampJavaTypeInfo (file:///Users/matt/code/deephaven.io/tools/run-examples/tmp/dh-core.js:678:8)
      at Object.stampJavaTypeInfo_0 (file:///Users/matt/code/deephaven.io/tools/run-examples/tmp/dh-core.js:687:55)
      at Object.stampJavaTypeInfo_1 (file:///Users/matt/code/deephaven.io/tools/run-examples/tmp/dh-core.js:4650:15)
      at Object.$lambda$2_0 (file:///Users/matt/code/deephaven.io/tools/run-examples/tmp/dh-core.js:23195:52)
      at Function.apply_141 (file:///Users/matt/code/deephaven.io/tools/run-examples/tmp/dh-core.js:23646:11)
      at lambda (file:///Users/matt/code/deephaven.io/tools/run-examples/tmp/dh-core.js:173:22)
      at Object.$lambda$11_5 (file:///Users/matt/code/deephaven.io/tools/run-examples/tmp/dh-core.js:31995:101)
      at Function.run_37 (file:///Users/matt/code/deephaven.io/tools/run-examples/tmp/dh-core.js:32543:9)
      at lambda (file:///Users/matt/code/deephaven.io/tools/run-examples/tmp/dh-core.js:173:22)
      at Function.onInvoke_238 (file:///Users/matt/code/deephaven.io/tools/run-examples/tmp/dh-core.js:30468:22)
      at lambda (file:///Users/matt/code/deephaven.io/tools/run-examples/tmp/dh-core.js:173:22) {
    '__java$exception': [Circular *1]
  }
```

**Additional details and attachments**

The rest of the docs examples ran without problem.

**Versions**
 - Deephaven: https://github.com/deephaven/deephaven-core/commit/ad97a9eb3da4fdff9a47a4c4797f0fba3a563d2a
