### ISSUE TITLE
Cancel in-progress CI jobs for PRs when new commits are pushed

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-core#4198]
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow

It might be as simple as adding

```yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
```

to all of the relevant workflows.
