### ISSUE TITLE
Long running `run_script` calls fail

### ISSUE THREAD

**Issue by chipkent** [deephaven/deephaven-core#5170]
```python
session.run_script('''import time
time.sleep(60*30)''')
```

![image](https://github.com/deephaven/deephaven-core/assets/5250374/e8fd62f6-fec6-48d3-b12f-30e54695fac2)

**Comment by nbauernfeind** [comment]
Are you connecting directly to the server, or is there an intermediate such as envoy?

The python client does not set a deadline/timeout explicitly. (It should not.)

This is what it looks like to set a deadline: (see: https://github.com/grpc/grpc-java/blob/master/examples/src/main/java/io/grpc/examples/deadline/DeadlineClient.java#L56-L57)
```python
      response = blockingStub.withDeadlineAfter(timeoutMillis, TimeUnit.MILLISECONDS)
          .sayHello(request);
```

Our client does this:
```python
        self._grpc_console_stub = console_pb2_grpc.ConsoleServiceStub(session.grpc_channel)
```
...
```python
    def run_script(self, server_script: str) -> Any:
        """Runs a Python script in the console."""
        self.start_console()

        try:
            response = self._grpc_console_stub.ExecuteCommand(
                console_pb2.ExecuteCommandRequest(
                    console_id=self.console_id,
                    code=server_script),
                metadata=self.session.grpc_metadata)
            return response
        except Exception as e:
            raise DHError("failed to execute a command in the console.") from e

```

So there is no deadline being set.

Your error says "Socket closed" and I suspect it is very likely you have an intermediate process that is not respecting our need for long running calls. If you have an envoy fronting the server, can you double the configuration for both a `stream_idle_timeout` of `0s` on the `envoy.filters.network.http_connection_manager` filter as well as grpc disabling of timeouts like in this route block (part of the same filter):

```yaml
                        - match: # Any GRPC call is assumed to be forwarded to the real service
                            prefix: "/"
                          route:
                            cluster: grpc-api
                            max_stream_duration:
                              grpc_timeout_header_max: 0s
                            timeout: 0s
```

I don't have any other disabled timeouts. Can you also verify whether the UI can wait that long by running the script via the repl?

@jmao-denver or @niloc132: do you know if the python client can keep its session alive if it's blocked waiting for 30m? (are background threads able to ping the server to keep the session alive?)

I'll need to poke around a little more ... but possibly while the primary single-threaded executor is held up sleeping that the shared executor threads end up blocking behind it completing (we can't grab the shared lock for any non-concurrent instantiation methods; so they will block). I don't believe that we need the shared executor to keep alive the session; I'm running a similar test (sleeping for 30m) from the web-ui to validate this claim (the test I'm running is using envoy but still has 26m to go).
