### ISSUE TITLE
Patch releases of jsapi-types getting dist-tag `latest` incorrectly

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-core#5572]
**Description**

When we publish a patch version of deephaven-core (and subsequently a patch version of the `@deephaven/jsapi-types` package), it should _not_ be labelled as `latest`.
For example, we previously published `v0.34.2`, which is the `latest` version. We then went back and released a patch to v0.33, and published `v0.33.4`. That should not have the dist-tag of `latest`, `latest` should still point to `v0.34.2`.
For web-client-ui packages, we set the dist tag to just the major version number of the release branch that is being patched, e.g. https://github.com/deephaven/web-client-ui/blob/37571633dd0be5b7a606bee45af10f6a7d09d4ec/lerna.json#L6

See screenshot below. v0.34.2 was published 13 days ago, and then we published a patch 0.33.4 yesterday, but that stole the `latest` tag.

**Additional details and attachments**
![image](https://github.com/deephaven/deephaven-core/assets/4505624/79c403ae-d143-4c99-bea7-97982e75611c)

**Comment by mofojed** [comment]
Fix would just be changing `latest` to the release branch name at https://github.com/deephaven/deephaven-core/blob/bf13489d48327e2e3d504e6be13020f30c46bd23/.github/workflows/publish-ci.yml#L120 (e.g. `v0.33`)

**Comment by mofojed** [comment]
From @devinrsmith :
> May need to be a bash script. You'll want to get the official version from gradle (as opposed to the branch name)

**Comment by devinrsmith** [comment]
There are a couple of GH tasks that call the `outputVersion` task and get the version:

```yaml
      - name: All Javadoc
        uses: burrunan/gradle-cache-action@v1
        with:
          job-id: allJavadoc
          arguments: --scan outputVersion combined-javadoc:allJavadoc
          gradle-version: wrapper
          
      - name: Get Deephaven Version
        id: dhc-version
        run: echo "version=$(cat build/version)" >> $GITHUB_OUTPUT
```
